services:
  web:
    build: .
    ports:
      - "5000:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - ENVIRONMENT=development
      - FLASK_DEBUG=1
      - TZ=America/New_York
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DAILY_API_KEY=${DAILY_API_KEY}
      - YOUR_DOMAIN=${YOUR_DOMAIN:-https://droply.live}
      - REPLIT_DEV_DOMAIN=droply.live
    command: python app.py

# Removed db service and depends_on

# volumes:
#   postgres_data: 