services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - ENVIRONMENT=production
      - FLASK_DEBUG=0
      - TZ=America/New_York
      - SECRET_KEY=${SECRET_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DAILY_API_KEY=${DAILY_API_KEY}
      - YOUR_DOMAIN=${YOUR_DOMAIN:-https://droply.live}
    command: python -m flask run --host=0.0.0.0 --port=5000
