version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - REPLIT_DEV_DOMAIN=${REPLIT_DEV_DOMAIN}
    command: python main.py

# Removed db service and depends_on

# volumes:
#   postgres_data: 